version: "3.9"  # optional since v1.27.0
services:
  web:
    env_file: .env
  #Use "build: ." If "context" i.e. path to the dockerfile is in the same folder/current folder/"."
    build:
      context: .
      dockerfile: Dockerfile
      target: development-env
      args:
        buildno: 1.1
        userdefinedargument: "Based on the commit xyz"
    ports:
      - "4242:3000"
    labels:
      name: "Pratik's Docker compose tutorial webapi on development environment."
    
  #Volumes created.
    volumes: 
      - .:/app